# -*- coding: utf-8 -*-
"""
/***************************************************************************
 imageLoader
                                 A QGIS plugin
 Loads and unloads images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-24
        copyright            : (C) 2022 by Drew
        email                : drew.bennett@ptsinternational.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load imageLoader class from file imageLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .image_loader import imageLoader
    return imageLoader(iface)



#import sys
#import os
#f = os.path.dirname(__file__)

#if not f in sys.path:
 #   sys.path.append(f)

#print(sys.path)


