# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_loader_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imageLoaderDockWidgetBase(object):
    def setupUi(self, imageLoaderDockWidgetBase):
        imageLoaderDockWidgetBase.setObjectName("imageLoaderDockWidgetBase")
        imageLoaderDockWidgetBase.resize(915, 660)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabs = QtWidgets.QTabWidget(self.mainWidget)
        self.tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setObjectName("tabs")
        self.runs = QtWidgets.QWidget()
        self.runs.setObjectName("runs")
        self.gridLayout = QtWidgets.QGridLayout(self.runs)
        self.gridLayout.setObjectName("gridLayout")
        self.runsWidget = runsView(self.runs)
        self.runsWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.runsWidget.setUniformRowHeights(True)
        self.runsWidget.setObjectName("runsWidget")
        self.gridLayout.addWidget(self.runsWidget, 1, 0, 1, 1)
        self.tabs.addTab(self.runs, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runBox = QtWidgets.QComboBox(self.tab)
        self.runBox.setObjectName("runBox")
        self.horizontalLayout.addWidget(self.runBox)
        self.selectRunButton = QtWidgets.QPushButton(self.tab)
        self.selectRunButton.setObjectName("selectRunButton")
        self.horizontalLayout.addWidget(self.selectRunButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.correctionsView = correctionsView(self.tab)
        self.correctionsView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.correctionsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.correctionsView.setObjectName("correctionsView")
        self.verticalLayout.addWidget(self.correctionsView)
        self.tabs.addTab(self.tab, "")
        self.images = QtWidgets.QWidget()
        self.images.setObjectName("images")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.images)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imagesView = imagesView(self.images)
        self.imagesView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.imagesView.setUniformRowHeights(True)
        self.imagesView.setItemsExpandable(True)
        self.imagesView.setObjectName("imagesView")
        self.verticalLayout_3.addWidget(self.imagesView)
        self.tabs.addTab(self.images, "")
        self.verticalLayout_4.addWidget(self.tabs)
        self.verticalLayout_2.addWidget(self.mainWidget)
        imageLoaderDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(imageLoaderDockWidgetBase)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(imageLoaderDockWidgetBase)

    def retranslateUi(self, imageLoaderDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        imageLoaderDockWidgetBase.setWindowTitle(_translate("imageLoaderDockWidgetBase", "PTS image loader v3.50"))
        self.tabs.setTabText(self.tabs.indexOf(self.runs), _translate("imageLoaderDockWidgetBase", "Runs"))
        self.runBox.setToolTip(_translate("imageLoaderDockWidgetBase", "<html><head/><body><p>Show corrections for this run.</p></body></html>"))
        self.selectRunButton.setToolTip(_translate("imageLoaderDockWidgetBase", "<html><head/><body><p>Select this run in the runs table.</p></body></html>"))
        self.selectRunButton.setText(_translate("imageLoaderDockWidgetBase", "Select run"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("imageLoaderDockWidgetBase", "Corrections"))
        self.tabs.setTabText(self.tabs.indexOf(self.images), _translate("imageLoaderDockWidgetBase", "Images"))
from image_loader.corrections_view import correctionsView
from image_loader.images_view import imagesView
from image_loader.runs_view import runsView
