# -*- coding: utf-8 -*-
"""
/***************************************************************************
 imageLoaderDockWidget
                                 A QGIS plugin
 Loads and unloads images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-24
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Drew
        email                : drew.bennett@ptsinternational.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal,QUrl,Qt

from .models.image_model_spatialite.image_model import imageModel
from .models.runs_model_spatialite import runs_model
from .models import setup_database
from .models.natural_sort import naturalSortFilterProxyModel


from .functions.load_frame_data import loadFrameData
from .functions.load_cracking import loadCracking
from .widgets import set_layers_dialog
from .functions import group_functions

from PyQt5.QtWidgets import QMenuBar,QFileDialog,QProgressDialog
from PyQt5 import QtGui
from PyQt5.QtSql import QSqlDatabase


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'image_loader_dockwidget_base.ui'))


dev = False#set to false for end user.

if dev:
    from . import test


class imageLoaderDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        
        super(imageLoaderDockWidget, self).__init__(parent)
        self.setupUi(self)
        
        self.layersDialog = set_layers_dialog.setLayersDialog(parent=self)
        self.setFile()
        #from image_loader import test
       # self.setFile(test.dbFile)#####good for debuging but user wont't have test
        
        self.loadButton.clicked.connect(self.loadDetails)
        self.markButton.clicked.connect(self.runsLoad)
        self.initTopMenu()
        self.runsBox.currentTextChanged.connect(self.setRun)
        self.setRun(self.runsBox.currentText())

        if dev:
            self.addDetails(self.im().addFolder(test.testFolder))


    def im(self):
        return self.fileDetailsView.model()


    def runsModel(self):
        return self.runsView.runsModel()


    def setRun(self,run):
        if self.im() is not None:
            self.im().setRun(run)



    #QFileDialog should return existing file or None.
    #handle actual opening
    #set file to '' for new.
    def setFile(self,file='untitled'):
        
        ext = os.path.splitext(file)[-1]
        
        if  ext in ['.db','.sqlite']:
            dbFile = file
        else:
            dbFile = ':memory:'
        
        self.file = file
        
        db = QSqlDatabase.addDatabase('QSPATIALITE','image_loader')
        db.setDatabaseName(dbFile)
        db.open()
                
        self.setWindowTitle('{file} - Image Loader'.format(file=file))
        setup_database.setupDb(db)
        
        self.fileDetailsView.setModel(imageModel(parent=self,db=db))
        
        m = runs_model.runsModel(parent=self,db=db)
        self.im().rowsChanged.connect(m.select)
        self.im().setLayers(self.layersDialog)
        self.runsBox.setModel(m)

        proxy = naturalSortFilterProxyModel(self)
        proxy.setSourceModel(m)
        self.runsView.setModel(proxy)
        
        if ext in ['csv','txt']:
            self.addDetails(self.im().addCsv(file))
        

    def initTopMenu(self):
        topMenu = QMenuBar(self.mainWidget)    
        
        fileMenu = topMenu.addMenu("File")
        newAct = fileMenu.addAction('New')
        newAct.triggered.connect(lambda:self.setFile())
        
        openAct = fileMenu.addAction('Open...')
        openAct.triggered.connect(self.openFile)
        
        saveAct = fileMenu.addAction('Save as...')
        saveAct.triggered.connect(self.save)
        
        ######################load
        detailsMenu = topMenu.addMenu("Image_details")
        fromFolderAct = detailsMenu.addAction('Find from folder...')
        fromFolderAct.triggered.connect(self.detailsFromFolder)

        layersMenu = topMenu.addMenu("Load layers")
        loadFramesAct = layersMenu.addAction('Load Spatial Frame Data...')
        loadFramesAct.triggered.connect(self.loadFrames)
        
 
        setupMenu = topMenu.addMenu("Setup")
        setLayers = setupMenu.addAction('Set layers and fields...')
        setLayers.triggered.connect(self.layersDialog.exec_)
        
 
        loadCracksAct = layersMenu.addAction('Load Cracking Data...')
        loadCracksAct.triggered.connect(self.loadCracks)        
        
        helpMenu = topMenu.addMenu('Help')
        openHelpAct = helpMenu.addAction('Open help (in your default web browser)')
        openHelpAct.triggered.connect(self.openHelp)        
        self.mainWidget.layout().setMenuBar(topMenu)



    def framesLayer(self):
        return self.layersDialog.framesLayer()

    def idField(self):
        return self.layersDialog.idField()
  
    def runField(self):
        return self.layersDialog.runField()
    

#opens help/index.html in default browser
    def openHelp(self):
        helpPath = os.path.join(os.path.dirname(__file__),'help','help.html')
        helpPath = 'file:///'+os.path.abspath(helpPath)
        QtGui.QDesktopServices.openUrl(QUrl(helpPath))

        

    #load iterable of details and maybe display cancellable progress bar.
   #QgsTask is very buggy. QProgressDialog much simpler.
    def loadDetails(self):
        
        details = self.im().getDetails()
        group_functions.removeChild('image_loader')#remove group
        progress = QProgressDialog("Loading images...","Cancel", 0, len(details),self)
        progress.setWindowModality(Qt.WindowModal)
        
        for i,d in enumerate(details):
            d.load()
            progress.setValue(i+1)
            if progress.wasCanceled():
                break
        progress.deleteLater()



    def loadFrames(self):
        f = QFileDialog.getOpenFileName(caption = 'Load Spatial Frame Data',filter = 'txt (*.txt)')
        if f:
            if f[0]:
                loadFrameData(f[0])



    def loadCracks(self):
        f = QFileDialog.getOpenFileName(caption = 'Load Crack data Data',filter = 'txt (*.txt)')
        if f:
            if f[0]:
                loadCracking(f[0])
                

    #open dialog and load csv/sqlite file
    def openFile(self):
        f = QFileDialog.getOpenFileName(caption = 'open',filter = '*.csv;;*.txt;;*.db;;*.sqlite;;*')[0]
        if f:
            self.setFile(f)
                

    
    def save(self):
        f = QFileDialog.getSaveFileName(caption = 'Save details',filter = 'csv (*.csv);;txt (*.txt);;sqlite (*.sqlite);;sqlite (*.db)')[0]
        if f:
            self.im().save(f)


#load rasters for selected runs in runsModel
    def runsLoad(self):
        if self.im() is not None and self.runsModel() is not None:
            self.runsModel().markInDetails()
            self.im().select()
            self.loadDetails()


    #load all tif files in folder and consider showing progress bar
    def detailsFromFolder(self):
        f = QFileDialog.getExistingDirectory(self,'Folder with images')
        if f:
            self.addDetails(self.im().addFolder(f))
            
           
            
    #find extents for list of details. allows cancelling with progressDialog       
    def findExtents(self,details):
        progress = QProgressDialog("finding image extents...","Cancel",0,len(details),self)
        progress.setWindowModality(Qt.WindowModal)
        progress.setWindowTitle("finding image extents...")
        progress.setMaximum(len(details))
            
        for i,d in enumerate(details):
            progress.setValue(i)
            if progress.wasCanceled():
                break
            d.findExtents()
            
    '''        
        #load list of details.
        #loads batchSize at time. small batchSize results in slow loading. too large results in progressbar updating slowly.
        
    '''    
    def addDetails(self,gen):
     #  print(details)
     
     #QProgressDialog(const QString &labelText, const QString &cancelButtonText, int minimum, int maximum, QWidget *parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags()
        progress = QProgressDialog("Adding image details...","Cancel",0,0,self)
        progress.setWindowModality(Qt.WindowModal)

        for i,le in gen:
            progress.setMaximum(le)
            progress.setValue(i)
            if progress.wasCanceled():
                break
        
        self.im().select()
        self.runsModel().select()
        #progress.deleteLater()    
            

    def closeEvent(self, event):
        self.closingPlugin.emit()
        QSqlDatabase.database('image_loader').close()
        event.accept()
