# -*- coding: utf-8 -*-
"""
/***************************************************************************
 imageLoaderDockWidget
                                 A QGIS plugin
 Loads and unloads images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-24
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Drew
        email                : drew.bennett@ptsinternational.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtWidgets import QMenuBar,QFileDialog,QProgressDialog
from PyQt5.QtSql import QSqlDatabase
from PyQt5 import QtGui

import logging

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal,QUrl,Qt
#from qgis.core import QgsMapLayerProxyModel,QgsFieldProxyModel

from image_loader.models.image_model import image_model,group_functions
from image_loader.models import runs_model,natural_sort
from image_loader import exceptions,regex_file_dialog

from image_loader.functions.load_frame_data import loadFrameData
from image_loader.functions import setup_database
from image_loader.functions.load_cracking import loadCracking
from image_loader.widgets import set_layers_dialog


logger = logging.getLogger(__name__)


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'image_loader_dockwidget_base.ui'))


class imageLoaderDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        
        logger.debug('__init__')
        super(imageLoaderDockWidget, self).__init__(parent)
        self.setupUi(self)
        
     #   self.layerBox.setFilters(QgsMapLayerProxyModel.PolygonLayer)
      #  self.fieldBox.setFilters(QgsFieldProxyModel.Int)

        
        dbFile = ":memory:"
        
        db = QSqlDatabase.addDatabase('QSPATIALITE')   #QSqlDatabase
        db.setDatabaseName(dbFile)
        if not db.open():
            raise exceptions.imageLoaderError('could not create database')
        
        #image_model.createTable(db)
        
        setup_database.setupDb(db)
        
        self.fileDetailsView.setModel(image_model.imageModel(parent=self,db=db))
        
        
        self.fileDetailsView.setColumnHidden(self.fileDetailsView.model().fieldIndex('pk'),True)
        self.fileDetailsView.setColumnHidden(self.fileDetailsView.model().fieldIndex('geom'),True)

        
       # runs_model.createTable(db)
        proxy = natural_sort.naturalSortFilterProxyModel(self)
        proxy.setSourceModel(runs_model.runsModel(parent=self,db=db))
        self.runsView.setModel(proxy)
        
        self.imageModel().dbChanged.connect(self.infoChange)
        #self.fileDetailsView.resizeColumnsToContents()


        self.loadButton.clicked.connect(self.load)
        
        
        self.layersDialog = set_layers_dialog.setLayersDialog(parent=self)
        
        self.initTopMenu()
        
       # self.layerBox.layerChanged.connect(self.layerChange)
     #   self.layerChange(self.getLayer())

       # self.fieldBox.fieldChanged.connect(self.fieldChange)
       # self.fieldChange(self.getField())
        
        

  #  def layerChange(self,layer):
   #      logger.debug('layerChange(%s)',layer)
   #      self.fieldBox.setLayer(layer)
   #      self.runsView.setLayer(layer)



  #  def fieldChange(self,field):
  #       logger.debug('fieldChange(%s)',field)
  #       self.runsView.setField(field)


    def imageModel(self):
        return self.fileDetailsView.model()


    def runsModel(self):
        return self.runsView.runsModel()


    def initTopMenu(self):
        topMenu = QMenuBar(self.mainWidget)       
        ######################load
        loadMenu = topMenu.addMenu("Image_details")
        
        loadCsvAct = loadMenu.addAction('Load image details from csv/txt...')
        loadCsvAct.triggered.connect(self.loadCsv)
                
        fromFolderAct = loadMenu.addAction('Find from folder...')
        fromFolderAct.triggered.connect(self.detailsFromFolder)

        saveCsvAct = loadMenu.addAction('Save to csv...')
        saveCsvAct.triggered.connect(self.saveToCsv)
        
        layersMenu = topMenu.addMenu("Load layers")
        loadFramesAct = layersMenu.addAction('Load Spatial Frame Data...')
        loadFramesAct.triggered.connect(self.loadFrames)
        
 
        setupMenu = topMenu.addMenu("Setup")
        setLayers = setupMenu.addAction('Set layers and fields...')
        setLayers.triggered.connect(self.layersDialog.exec_)
        
 
        loadCracksAct = layersMenu.addAction('Load Cracking Data...')
        loadCracksAct.triggered.connect(self.loadCracks)        
        
        helpMenu = topMenu.addMenu('Help')
        openHelpAct = helpMenu.addAction('Open help (in your default web browser)')
        openHelpAct.triggered.connect(self.openHelp)        
        self.mainWidget.layout().setMenuBar(topMenu)



    def framesLayer(self):
        return self.layersDialog.framesLayer()

    def idField(self):
        return self.layersDialog.idField()

   # def getLayer(self):
     #   return self.layerBox.currentLayer()
    

   # def getField(self):
    #    return self.fieldBox.currentField()


    def infoChange(self):
   #     self.runsModel().updateTable()
        if isinstance(self.runsModel(),runs_model.runsModel):
            self.runsModel().select()


#opens help/index.html in default browser
    def openHelp(self):
        helpPath = os.path.join(os.path.dirname(__file__),'help','help.html')
        helpPath = 'file:///'+os.path.abspath(helpPath)
        QtGui.QDesktopServices.openUrl(QUrl(helpPath))

        
    #load images.
    def load(self):
        self.loadDetails(self.runsModel().getDetails())


    #load iterable of details and maybe display cancellable progress bar.
   #QgsTask is very buggy. QProgressDialog much simpler.
    def loadDetails(self,details):
        group_functions.removeChild('image_loader')#remove group
        progress = QProgressDialog("Loading images...","Cancel", 0, len(details),self)
        progress.setWindowModality(Qt.WindowModal)
        for i,d in enumerate(details):
            d.load()
            progress.setValue(i+1)
            if progress.wasCanceled():
                break
        progress.deleteLater()


    def loadFrames(self):
        f = QFileDialog.getOpenFileName(caption = 'Load Spatial Frame Data',filter = 'txt (*.txt)')
        if f:
            if f[0]:
                loadFrameData(f[0])
        


    def loadCracks(self):
        f = QFileDialog.getOpenFileName(caption = 'Load Crack data Data',filter = 'txt (*.txt)')
        if f:
            if f[0]:
                loadCracking(f[0])
                


    def loadCsv(self):
        logger.debug('loadCsv')
        f = QFileDialog.getOpenFileName(caption = 'Load details csv',filter = 'csv (*.csv);;txt (*.txt)')
        if f:
            if f[0]:
                self.imageModel().clearTable()
                self.imageModel().loadCsv(f[0])



    #unused
    #load 'raster image load' txt file
    def loadRil(self):
        logging.debug('loadRil')
        
    #    d = QFileDialog(self)
     #   d.setNameFilters(['txt (*raster image load*.txt)'])
  #  #    d.exec()
     #   f = d.selectedFiles()
        
       # f = QFileDialog.getOpenFileName(caption = 'Load details csv',filter = 'txt (*raster image load*.txt)')
        f = regex_file_dialog.getFileName(
            filterExpression = '.*raster image load.*',
            parent = self,
            caption = 'select Raster Image Load file',
            extensionFilter = "txt (*.txt)",
            caseSensitive = False)
        
        #f = QFileDialog.getOpenFileName(caption = 'Load details csv',filter = '*.txt;;*')[0]
        if f:
            if f[0]:
                self.imageModel().clearTable()
                self.imageModel().loadCsv(f[0])
        

    
    def saveToCsv(self):
        f = QFileDialog.getSaveFileName(caption = 'Save details to csv',filter = 'csv (*.csv);;txt (*.txt)')[0]
        if f:
            self.imageModel().saveAsCsv(f)


    def detailsFromFolder(self):
        logging.debug('detailsFromFolder')
        f = QFileDialog.getExistingDirectory(self,'Folder with images')
        if f:
            self.imageModel().fromFolder(f)


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
